In [139]:
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd
import json
import os
from dotenv import load_dotenv
from sodapy import Socrata
import chromedriver_binary
#from src.cleaning3 import *
import folium
from folium.plugins import HeatMapWithTime as HMWT
from folium.plugins import HeatMap as HM
from folium import plugins
import warnings
warnings.simplefilter('ignore')

In [140]:
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time 
import urllib3

In [141]:
url='https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
html=req.get(url).content
html[:10]

b'<!DOCTYPE '

In [142]:
soup=bs(html, 'html.parser')
type(soup)

bs4.BeautifulSoup

In [143]:
tabla=soup.find_all('table')[2]
type(tabla)

bs4.element.Tag

In [144]:
filas=tabla.find_all('tr')
filas=[f.text.strip().split('\n') for f in filas][2:]
filas[:2]

[['United States',
  'Americas',
  '22,939,580',
  '2021',
  '20,893,746',
  '2020',
  '20,936,600',
  '2020'],
 ['China',
  'Asia',
  '16,862,979',
  '[n 2]2021',
  '14,722,801',
  '[n 3]2020',
  '14,722,731',
  '2020']]

In [145]:
final=[]
for e in filas:
    tmp=[]
    for st in e:
        if st!='':
            tmp.append(st)
    final.append(tmp)   
final[0]

['United States',
 'Americas',
 '22,939,580',
 '2021',
 '20,893,746',
 '2020',
 '20,936,600',
 '2020']

In [146]:
col=['country','region','gdp 2021 (us$ million)','Year_','GDP (UN)','Year1','GDP (WB)','Year2']

In [147]:
#df
data=final[0:]  #no coger las celdas combinadas
df=pd.DataFrame(data, columns=col)
df.head(10)

,country,region,gdp 2021 (us$ million),Year_,GDP (UN),Year1,GDP (WB),Year2
0,United States,Americas,"22,939,580",2021,"20,893,746",2020,"20,936,600",2020
1,China,Asia,"16,862,979",[n 2]2021,"14,722,801",[n 3]2020,"14,722,731",2020
2,Japan,Asia,"5,103,110",2021,"5,057,759",2020,"4,975,415",2020
3,Germany,Europe,"4,230,172",2021,"3,846,414",2020,"3,806,060",2020
4,United Kingdom,Europe,"3,108,416",2021,"2,764,198",2020,"2,707,744",2020
5,India,Asia,"2,946,061",2021,"2,664,749",2020,"2,622,984",2020
6,France,Europe,"2,940,428",2021,"2,630,318",2020,"2,603,004",2020
7,Italy,Europe,"2,120,232",2021,"1,888,709",2020,"1,886,445",2020
8,Canada,Americas,"2,015,983",2021,"1,644,037",2020,"1,643,408",2020
9,South Korea,Asia,"1,823,852",2021,"1,637,896",2020,"1,630,525",2020

In [148]:
df.head(10)

,country,region,gdp 2021 (us$ million),Year_,GDP (UN),Year1,GDP (WB),Year2
0,United States,Americas,"22,939,580",2021,"20,893,746",2020,"20,936,600",2020
1,China,Asia,"16,862,979",[n 2]2021,"14,722,801",[n 3]2020,"14,722,731",2020
2,Japan,Asia,"5,103,110",2021,"5,057,759",2020,"4,975,415",2020
3,Germany,Europe,"4,230,172",2021,"3,846,414",2020,"3,806,060",2020
4,United Kingdom,Europe,"3,108,416",2021,"2,764,198",2020,"2,707,744",2020
5,India,Asia,"2,946,061",2021,"2,664,749",2020,"2,622,984",2020
6,France,Europe,"2,940,428",2021,"2,630,318",2020,"2,603,004",2020
7,Italy,Europe,"2,120,232",2021,"1,888,709",2020,"1,886,445",2020
8,Canada,Americas,"2,015,983",2021,"1,644,037",2020,"1,643,408",2020
9,South Korea,Asia,"1,823,852",2021,"1,637,896",2020,"1,630,525",2020

In [149]:
df=df.drop(columns=['Year_','GDP (UN)','Year1','GDP (WB)','Year2'])
df

                              country    region gdp 2021 (us$ million)
0                       United States  Americas             22,939,580
1                               China      Asia             16,862,979
2                               Japan      Asia              5,103,110
3                             Germany    Europe              4,230,172
4                      United Kingdom    Europe              3,108,416
5                               India      Asia              2,946,061
6                              France    Europe              2,940,428
7                               Italy    Europe              2,120,232
8                              Canada  Americas              2,015,983
9                         South Korea      Asia              1,823,852
10                             Russia    Europe              1,647,568
11                             Brazil  Americas              1,645,837
12                          Australia   Oceania              1,610,556
13                              Spain    Europe              1,439,958
14                             Mexico  Americas              1,285,518
15                          Indonesia      Asia              1,150,245
16                               Iran      Asia              1,081,383
17                        Netherlands    Europe              1,007,562
18                       Saudi Arabia      Asia                842,588
19                        Switzerland    Europe                810,830
20                             Turkey      Asia                795,952
21                             Taiwan      Asia                785,589
22                             Poland    Europe                655,332
23                             Sweden    Europe                622,365
24                            Belgium    Europe                581,848
25                           Thailand      Asia                546,223
26                            Ireland    Europe                516,253
27                            Austria    Europe                481,209
28                            Nigeria    Africa                480,482
29                             Israel      Asia                467,532
30                          Argentina  Americas                455,172
31                             Norway    Europe                445,507
32                       South Africa    Africa                415,315
33               United Arab Emirates      Asia                410,158
34                            Denmark    Europe                396,666
35                              Egypt    Africa                396,328
36                        Philippines      Asia                393,737
37                          Singapore      Asia                378,645
38                           Malaysia      Asia                371,114
39                          Hong Kong      Asia                369,722
40                            Vietnam      Asia                368,002
41                         Bangladesh      Asia                355,689
42                              Chile  Americas                331,250
43                           Colombia  Americas                300,791
44                            Finland    Europe                296,016
45                            Romania    Europe                287,279
46                           Pakistan      Asia                347,340
47                     Czech Republic    Europe                276,914
48                           Portugal    Europe                251,709
49                        New Zealand   Oceania                247,640
50                               Peru  Americas                225,858
51                             Greece    Europe                211,645
52                               Iraq      Asia                201,472
53                         Kazakhstan      Asia                194,024
54                            Ukraine    Europe                181,038
55                            Hungary    Europe                180,959
56                              Qatar      Asia                169,184
57                            Algeria    Africa                163,812
58                             Kuwait      Asia                132,266
59                            Morocco    Africa                126,035
60                           Slovakia    Europe                116,748
61                              Kenya    Africa                109,491
62                               Cuba  Americas                    N/A
63                        Puerto Rico  Americas                106,576
64                            Ecuador  Americas                104,483
65                           Ethiopia    Africa                 92,757
66                 Dominican Republic  Americas                 89,502
67                         Luxembourg    Europe                 83,771
68                          Guatemala  Americas                 83,305
69                          Sri Lanka      Asia                 80,785
70                               Oman      Asia                 80,611
71                           Bulgaria    Europe                 77,907
72                              Ghana    Africa                 75,487
73                             Angola    Africa                 70,339
74                           Tanzania    Africa                 69,238
75                        Ivory Coast    Africa                 68,845
76                            Myanmar      Asia                 66,740
77                            Belarus    Europe                 65,754
78                         Uzbekistan      Asia                 65,503
79                            Lebanon      Asia                 19,126
80                            Croatia    Europe                 63,399
81                          Lithuania    Europe                 62,635
82                         Costa Rica  Americas                 61,178
83                           Slovenia    Europe                 60,890
84                             Serbia    Europe                 60,669
85                             Panama  Americas                 60,121
86                            Uruguay  Americas                 60,108
87                           DR Congo    Africa                 54,832
88                       Turkmenistan      Asia                 53,087
89                         Azerbaijan      Asia                 52,645
90                             Jordan      Asia                 45,344
91                          Venezuela  Americas                 44,893
92                           Cameroon    Africa                 44,806
93                             Uganda    Africa                 43,243
94                            Tunisia    Africa                 42,733
95                            Bahrain      Asia                 39,104
96                            Bolivia  Americas                 38,547
97                             Latvia    Europe                 37,199
98                           Paraguay  Americas                 36,973
99                            Estonia    Europe                 36,039
100                             Sudan    Africa                 35,919
101                             Nepal      Asia                 34,265
102                             Macau      Asia                 29,223
103                       El Salvador  Americas                 27,665
104                           Senegal    Africa                 27,576
105                             Libya    Africa                 27,300
106                            Cyprus      Asia                 26,546
107                  Papua New Guinea   Oceania                 26,461
108                          Honduras  Americas                 26,325
109                          Cambodia      Asia                 26,080
110                          Zimbabwe    Africa                 25,791
111                           Iceland    Europe                 25,476
112                            Zambia    Africa                 21,699
113            Bosnia and Herzegovina    Europe                 21,692
114               Trinidad and Tobago  Americas                 21,599
115                             Haiti  Americas                 20,143
116                       Afghanistan      Asia                 19,938
117                      Burkina Faso    Africa                 19,932
118                              Mali    Africa                 19,563
119                             Yemen      Asia                 19,471
120                              Laos      Asia                 19,375
121                             Gabon    Africa                 18,293
122                             Benin    Africa                 18,067
123                           Georgia      Asia                 17,846
124                          Botswana    Africa                 17,605
125                         Palestine      Asia                 17,343
126                           Albania    Europe                 16,770
127                            Guinea    Africa                 16,724
128                             Malta    Europe                 16,695
129                       North Korea      Asia                    N/A
130                        Mozambique    Africa                 15,833
131                            Brunei      Asia                 15,686
132                             Niger    Africa                 15,637
133                             Syria      Asia                 60,043
134                           Jamaica  Americas                 14,857
135                          Mongolia      Asia                 14,280
136                        Madagascar    Africa                 14,101
137                   North Macedonia    Europe                 13,885
138                           Armenia      Asia                 13,612
139                         Nicaragua  Americas                 13,397
140                             Congo    Africa                 12,744
141                 Equatorial Guinea    Africa                 12,528
142                           Moldova    Europe                 12,396
143                              Chad    Africa                 12,345
144                           Namibia    Africa                 12,213
145                            Malawi    Africa                 12,150
146                         Mauritius    Africa                 10,998
147                           Bahamas  Americas                 10,681
148                            Rwanda    Africa                 10,395
149                     New Caledonia   Oceania                    N/A
150                        Mauritania    Africa                  9,164
151                            Kosovo    Europe                  8,958
152                              Togo    Africa                  8,493
153                        Kyrgyzstan      Asia                  8,150
154                        Tajikistan      Asia                  8,104
155                           Bermuda  Americas                    N/A
156                            Guyana  Americas                  7,395
157                     Liechtenstein    Europe                    N/A
158                            Monaco    Europe                    N/A
159                    Cayman Islands  Americas                    N/A
160                              Guam   Oceania                    N/A
161                  French Polynesia   Oceania                    N/A
162                        Montenegro    Europe                  5,494
163                           Somalia    Africa                  5,424
164                          Barbados  Americas                  4,648
165                              Fiji   Oceania                  4,639
166                          Maldives      Asia                  4,573
167                          Eswatini    Africa                  4,517
168                      Sierra Leone    Africa                  4,407
169                          Djibouti    Africa                  3,654
170                           Liberia    Africa                  3,384
171                       South Sudan    Africa                  3,263
172                           Andorra    Europe                  3,213
173                           Burundi    Africa                  3,193
174                         Greenland  Americas                    N/A
175                             Aruba  Americas                  2,865
176                          Suriname  Americas                  2,817
177                           Curaçao  Americas                    N/A
178          Central African Republic    Africa                  2,587
179                            Bhutan      Asia                  2,480
180                           Lesotho    Africa                  2,478
181                           Eritrea    Africa                  2,254
182                            Gambia    Africa                  2,042
183                            Belize  Americas                  1,909
184                        Cape Verde    Africa                  1,886
185                        San Marino    Europe                  1,728
186                          Zanzibar    Africa                    N/A
187                       Saint Lucia  Americas                  1,715
188                        East Timor      Asia                  1,697
189                   Solomon Islands   Oceania                  1,649
190                     Guinea-Bissau    Africa                  1,592
191            British Virgin Islands  Americas                    N/A
192               Antigua and Barbuda  Americas                  1,405
193                        Seychelles    Africa                  1,288
194                           Comoros    Africa                  1,281
195          Northern Mariana Islands   Oceania                    N/A
196                           Grenada  Americas                  1,083
197                           Vanuatu   Oceania                    999
198             Saint Kitts and Nevis  Americas                    976
199          Turks and Caicos Islands  Americas                    N/A
200                      Sint Maarten  Americas                    N/A
201                             Samoa   Oceania                    780
202  Saint Vincent and the Grenadines  Americas                    769
203                    American Samoa   Oceania                    N/A
204                          Dominica  Americas                    571
205             São Tomé and Príncipe    Africa                    534
206                             Tonga   Oceania                    501
207                        Micronesia   Oceania                    404
208                      Cook Islands   Oceania                    N/A
209                          Anguilla  Americas                    N/A
210                  Marshall Islands   Oceania                    241
211                          Kiribati   Oceania                    232
212                             Palau   Oceania                    208
213                             Nauru   Oceania                    133
214                        Montserrat  Americas                    N/A
215                            Tuvalu   Oceania                     65

In [151]:
df.to_csv('gdp.csv', index=False)